# Generated by Django 5.2.1 on 2025-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('quiz', 'Multiple Choice Quiz'), ('spelling', 'Spelling Game'), ('matching', 'Matching Pairs Game'), ('puzzle', 'Drag-and-Drop Puzzle')], default='quiz', max_length=20),
        ),
    ]
