# Generated by Django 5.2.1 on 2025-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Math', 'Math'), ('Technology', 'Technology'), ('Engineering', 'Engineering')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_a',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_b',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_c',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_d',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
