# Generated by Django 5.2.1 on 2025-05-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_quizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='puzzles/')),
                ('options', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
