# Generated by Django 5.2.1 on 2025-05-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_puzzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=100)),
                ('match', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='matching/')),
            ],
        ),
    ]
