# Generated by Django 5.2.1 on 2025-05-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_matchingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='spelling/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='spelling_audio/')),
            ],
        ),
    ]
