# Generated by Django 5.2.1 on 2025-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_spellingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingitem',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spellingitem',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
