# Generated by Django 5.2.1 on 2025-09-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_matchingitem_explanation_puzzle_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameCategory',
            new_name='GameLevel',
        ),
    ]
